server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

discord:
  bot-token: "MTM4NDI3MjY4NTUxMjUyMzg0Nw.GXJI4t.4TO2qytq9V8EK0Pxh0v2xC7_-OORbuV8wmpn84"
  channel-id: "851515512525029388"