server:
  port: 8080

reddit:
  subreddits:
    - name: argentina
      limit: 25
    - name: memes
      limit: 25
    - name: shitposting
      limit: 25
    - name : ArgentinaBenderStyle
      limit : 25

scheduling:
  fetch-interval-ms: 150000      # 2.5 minutes = 2 min 30 sec
  post-interval-ms: 15000        # 30 seconds

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

discord:
  bot-token: "MTM4NDI3MjY4NTUxMjUyMzg0Nw.GRluGM.lk0S7RH6VK6OZ-4xIVzxKzcFhJpU8ZFi1AE7NA"
  channel-id: "1384302033385033751"